### ISSUE TITLE
Error while using this package - $R

### ISSUE THREAD

**Issue by rameshmonad** [imperavi/vue-redactor#1]
vue.js:597 [Vue warn]: Error in mounted hook: "ReferenceError: $R is not defined"

**Comment by Peelz** [comment]
I have same issue.

**Comment by Peelz** [comment]
I solved this issue by
comment this line 
`
var app = $R(this.$refs.redactor, this.config);
`

and add this instead
`
var app = $(this.$el).redactor(this.config)
`

**Comment by dg1203** [comment]
Hi, i have a similar problem.
I have this in my component $R(this.$refs.redactor, this.config); , and I try to test it in Vue, but I have this error ReferenceError: $R is not defined when i starting unit test. Anybody can help me with this issue?
