### ISSUE TITLE
Vue3 compatibility

### ISSUE THREAD

**Issue by vikramsra** [imperavi/vue-redactor#10]
Team is the editor compatible with vue3 as we want to purchase it for our tool.

**Comment by imperavi** [comment]
Hi,
We are working on a new component for Vue3.

**Comment by guhweb** [comment]
one year later... news?

**Comment by mathiasselleslach** [comment]
@imperavi , is there any update to be shared here? :-)

**Comment by michaelvalenti** [comment]
@imperavi any update??
