### ISSUE TITLE
Help implementing

### ISSUE THREAD

**Issue by nam-co** [imperavi/vue-redactor#4]
Hi, I was wondering how to implement Vue-redactor in a already set vue element, would this be ok? thanks for the help

```js
new Vue({
  el: '#app',
  data: {
     something_else: true,
     content: '<h1>Hello and welcome</h1>',
     configOptions: {
           plugins: ['table']
     }
  },
  methods: {
  }
})
```

**Comment by web3devin** [comment]
Please provide the html for the page that you are trying to enable vue-redactor on.

This package adds a global component to Vue that lets you call `<Redactor v-model="content" :config="configOptions" />` from anywhere in your DOM.

If you are asking about how to add `something_else` to the component, you can do something like this...
```html
<Redactor v-model="content" :config="configOptions" :another-prop="something_else" />
```

**Comment by nam-co** [comment]
Hi Devin, this works great, I finally bought redactor and Im very happy, thank you, I got some notes hope you consider for a future version

1. Target in links modal, so it can be selected by user (like in edit image: “Open link in new tab”)
2. Is there a way to make the toolbarFixed dark mode like the air version? 
3. In edit images, why not put max width/height and automatically set width to 100% (mobile first)
4. is there a way to refresh images.json list
5. is there a way to stop drag toolbar icon? it happens a lot and it inserts the script url to the content

Thanks Devin, excellent wysiwyg editor

**Comment by web3devin** [comment]
@nam-co I didn't create Redactor. The credit goes to @imperavi. However, I will try to answer your questions.

> 1. Target in links modal, so it can be selected by user (like in edit image: “Open link in new tab”)
> 2. Is there a way to make the toolbarFixed dark mode like the air version?
> 3. In edit images, why not put max width/height and automatically set width to 100% (mobile first)

You can submit feature requests in the [support page while logged in.](https://imperavi.com/account/support/)

> 4. is there a way to refresh images.json list
> 5. is there a way to stop drag toolbar icon? it happens a lot and it inserts the script url to the content

If you want to go into more detail I might be able to help, but otherwise you can use the same support form above for any assistance with Redactor. 😄

**Comment by nam-co** [comment]
Hi @web3devin , sorry I didn't notice this wasn't from imperavi , thanks for the implementation

Devin Im trying to use it on laravel with something like:
  <Redactor v-model="desc_es" :config="redactor_configOptions" />
  <textarea v-model="desc_es" name="content[desc][es]"></textarea>

but when I submit this inside a form, the request comes empty (content[desc][es]), any ideas why?

Thanks

**Comment by web3devin** [comment]
@nam-co
Would you be able to provide more information on how you are using this package and attempting to post the form?

It should work using either the 1 way data binding example in this repo. For instance:

```vue
<Redactor v-model="desc_es" name="content[desc][es]"></Redactor>
```
