### ISSUE TITLE
Source editing is broken due to escaping and <p> wrapping

### ISSUE THREAD

**Issue by chris-ritsen** [imperavi/vue-redactor#6]
[https://imperavi.com/redactor/examples/initialization/vue-component/](https://imperavi.com/redactor/examples/initialization/vue-component/)
Use either one of the editors and enable the HTML editing mode. 

Enter a `<` and it will add the following:
`<p>&lt;</p>`

Enter any other text and it will be wrapped in a paragraph after a short delay. Typing `abcd` slowly will show as:
`<p>a</p>`
`<p>b</p>`
`<p>c</p>`
`<p>d</p>`

**Comment by robfrancken** [comment]
Is this going to get fixed?
